color: null
description: null
fieldLayouts:
  cf89bbb6-c266-4d12-92d0-22d25da1c872:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-26T19:15:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Interner Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 12df8b18-cb74-407b-8fb4-63284541791e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-26T19:19:05+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 501708d6-7abe-4fa9-9f92-2ccd61e530f7
            userCondition: null
          -
            dateAdded: '2025-11-26T19:19:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ec8bc776-3089-49fb-8891-4559bcbb37a3 # Links
            handle: navigationLink
            includeInCards: false
            instructions: null
            label: 'Navigation Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 782ddd9a-768e-4add-84d8-6d9f0753c227
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b17f768f-09da-4ad7-a26a-c7dfe700a142
        userCondition: null
handle: navigation
hasTitleField: true
icon: null
name: Navigation
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
