dateModified: 1764185877
email:
  fromEmail: dev@profitlich.ch
  fromName: 'Profitlich DEV'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  lokal:
    hasUrls: true
    name: Lokal
    settings:
      path: '@assetBasePath'
    type: craft\fs\Local
    url: '@assetBaseUrl'
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0e793c4c-3298-4c14-a50e-fe050eeaee18: Startseite # Startseite
    1ce458b1-c5ff-40c2-bad8-2ef7bffa8003: Text # Text
    44fec1ae-cc09-42b5-b6a8-1c301d066c04: Projektbilder # Projektbilder
    73f201e5-ad16-409e-aad7-af99f7e14761: Teasers # Teasers
    84b612e4-4c88-4c37-8daf-af7b33fdfa22: Navigation # Navigation
    84c06b02-ca2f-4cc8-8286-9ff9f9a1eccb: Landingpage # Landingpage
    396abe4e-d4af-4c68-a2fb-7a3bce13f340: 'SEO Bildbeschreibung' # SEO Bildbeschreibung
    0396ff1d-5e87-4504-952e-1935bb565bf6: Text # Text
    10120e23-43ba-494f-ba6c-7241058df713: Startseite # Startseite
    18952c35-98c2-44eb-b5bc-5bf8cc8829c8: TeaserSection # TeaserSection
    40535b60-d662-44ba-97fa-7aecf43c6ea6: Teasers # Teasers
    12994855-fd13-4d38-8ad9-156bb1960e74: Projektbilder # Projektbilder
    bac239f3-c626-43b7-9726-0a62539fdd46: Teaser # Teaser
    c0847a8d-414f-4497-81a5-0bb43568b583: Navigation # Navigation
    c81f04dd-a4dc-4e6f-a97b-5ce6004b8cf8: 'Profitlich DEV' # Profitlich DEV
    c2146f3a-86c4-4929-ad3b-bfa61123b4c1: Simple # Simple
    cdc8fe6c-761a-46b0-895a-4df17d4a4fc8: Landingpages # Landingpages
    e667dda0-024e-49cf-b865-a2bb0a7c491e: 'SEO Meta Description' # SEO Meta Description
    e814380a-f915-44b8-92b3-a767fa94f64a: 'Profitlich DEV' # Profitlich DEV
    ec8bc776-3089-49fb-8891-4559bcbb37a3: Links # Links
    f0300c95-552b-49b5-9351-7ad29f907352: Blocks # Blocks
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  csp:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      baseUri:
        -
          - "'self'"
      connectSrc:
        -
          - "'self'"
        -
          - 'https://*.googleapis.com'
        -
          - '*.google.com'
        -
          - 'https://*.gstatic.com'
        -
          - 'wss://*.ddev.site:5173'
      cspEnabled: true
      cspMode: tag
      cspOptions:
        - defaultSrc
        - scriptSrc
        - styleSrc
        - styleSrcAttr
        - styleSrcElem
        - imgSrc
        - connectSrc
        - fontSrc
        - frameSrc
        - formAction
        - baseUri
      defaultSrc:
        -
          - "'none'"
      fontSrc:
        -
          - "'self'"
        -
          - 'https://fonts.gstatic.com'
      formAction:
        -
          - "'self'"
      frameSrc:
        -
          - '*.google.com'
      headerProtection:
        -
          - Referrer-Policy
          - strict-origin-when-cross-origin
        -
          - Strict-Transport-Security
          - max-age=31536000;includeSubDomains;preload
        -
          - X-Content-Type-Options
          - nosniff
        -
          - X-Frame-Options
          - SAMEORIGIN
        -
          - X-Xss-Protection
          - '1; mode=block'
      imgSrc:
        -
          - "'self'"
        -
          - 'https://*.googleapis.com'
        -
          - 'https://*.gstatic.com'
        -
          - '*.google.com'
        -
          - '*.googleusercontent.com'
      modeOptions:
        -
          __assoc__:
            -
              - label
              - 'Response Headers'
            -
              - value
              - header
        -
          __assoc__:
            -
              - label
              - 'Meta Tags'
            -
              - value
              - tag
        -
          __assoc__:
            -
              - label
              - 'Report Only'
            -
              - value
              - report
      policyOptions:
        __assoc__:
          -
            - defaultSrc
            - default-src
          -
            - scriptSrc
            - script-src
          -
            - scriptSrcAttr
            - script-src-attr
          -
            - scriptSrcElem
            - script-src-elem
          -
            - styleSrc
            - style-src
          -
            - styleSrcAttr
            - style-src-attr
          -
            - styleSrcElem
            - style-src-elem
          -
            - imgSrc
            - img-src
          -
            - connectSrc
            - connect-src
          -
            - fontSrc
            - font-src
          -
            - objectSrc
            - object-src
          -
            - mediaSrc
            - media-src
          -
            - frameSrc
            - frame-src
          -
            - sandbox
            - sandbox
          -
            - reportUri
            - report-uri
          -
            - childSrc
            - child-src
          -
            - formAction
            - form-action
          -
            - frameAncestors
            - frame-ancestors
          -
            - pluginTypes
            - plugin-types
          -
            - baseUri
            - base-uri
          -
            - reportTo
            - report-to
          -
            - workerSrc
            - worker-src
          -
            - manifestSrc
            - manifest-src
          -
            - prefetchSrc
            - prefetch-src
          -
            - navigateTo
            - navigate-to
      protectionEnabled: true
      scriptSrc:
        -
          - "'self'"
      styleSrc:
        -
          - "'self'"
        -
          - 'https://fonts.googleapis.com'
      styleSrcAttr:
        -
          - "'self'"
        -
          - "'unsafe-inline'"
      styleSrcElem:
        -
          - "'self'"
        -
          - "'unsafe-inline'"
  imager-x:
    edition: pro
    enabled: true
    licenseKey: KU32LJZPYKL71P52HFU03HNL
    schemaVersion: 4.0.0
  obfuscator:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  password-policy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      cases: true
      maxLength: 160
      minLength: 20
      numbers: true
      showStrengthIndicator: true
      symbols: true
  simplemap:
    edition: pro
    enabled: true
    licenseKey: KW1SS54N2K3A6KBM3H0WKF4E
    schemaVersion: 3.4.2
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Profitlich DEV'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
