defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 84c06b02-ca2f-4cc8-8286-9ff9f9a1eccb # Landingpage
handle: landingpages
maxAuthors: 1
name: Landingpages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c81f04dd-a4dc-4e6f-a97b-5ce6004b8cf8: # Profitlich DEV
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: afce15f2-4cf8-4998-8525-0ad186764a51
type: structure
