defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 84b612e4-4c88-4c37-8daf-af7b33fdfa22 # Navigation
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c81f04dd-a4dc-4e6f-a97b-5ce6004b8cf8: # Profitlich DEV
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
