defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 18952c35-98c2-44eb-b5bc-5bf8cc8829c8 # TeaserSection
handle: teasers
maxAuthors: 1
name: Teasers
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c81f04dd-a4dc-4e6f-a97b-5ce6004b8cf8: # Profitlich DEV
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
